
obj-y :=
obj-y += os_async_queue.o
obj-y += os_broadcast.o
obj-$(CONFIG_EVDRIVER) += os_evdriver.o
obj-y += os_log.o
obj-y += os_misc.o
obj-y += os_mm.o
obj-y += os_msg.o
obj-y += os_multicast.o
obj-y += os_queue.o
obj-y += os_stdlibc.o
obj-y += os_task.o
obj-y += os_thread.o
obj-y += os_threadpool.o
obj-y += os_tcp_server.o
obj-y += os_tcp_client.o
obj-y += os_sys.o

