
obj-y :=
obj-y += os_async_queue.o
obj-y += os_broadcast.o
obj-y += os_evdriver.o
obj-y += os_log.o
obj-y += os_misc.o
obj-y += os_mm.o
obj-y += os_msg.o
obj-y += os_multicast.o
obj-y += os_queue.o
obj-y += os_stdlibc.o
obj-y += os_task.o
obj-y += os_thread.o
obj-y += os_threadpool.o

obj-y += glib/

