
obj-y :=
obj-y += sample.o
obj-y += task_show.o
obj-y += task_json.o
obj-y += task_broadcast.o
#obj-y += task_multicast.o
obj-y += mm_broadcast.o

obj-y += tcp_client.o
obj-y += tcp_server.o
obj-y += udp_tcp_client.o
obj-y += udp_tcp_server.o


