####################################################
# Make Function
####################################################


# dir , lib name , suffix ,configure args
define auto_make_install_compressed_lib
	@echo "[1;33m" ">>>>>>> Build File: $(2)$(3)" "[0;39m" ;
	@set -x;
	tar -zxf $(1)/$(2)$(3) -C $(1)/ ;
	cd $(1)/$(2) && ./configure $(4) && make -j8 && make install;
endef

# dir , lib name , suffix ,configure args
define auto_make_install_compressed_lib_once
	@echo "[1;33m" ">>>>>>> Build File: $(2)$(3)" "[0;39m" ;
	@set -x;
	@if [ ! -d $(1)/$(2) ]; then \
	{\
		tar -zxf $(1)/$(2)$(3) -C $(1)/ ;\
		cd $(1)/$(2) && ./configure $(4) && make -j8 && make install;\
	};\
	else echo "[1;32m" "$(2): nothing to do!!! " "[0;39m" ;\
	fi
endef

# dir , lib name , suffix ,configure args
define auto_make_install_compressed_lib_once_dirty
	@echo "[1;33m" ">>>>>>> Build File: $(2)$(3)" "[0;39m" ;
	@set -x;
	@if [ ! -d $(1)/$(2) ]; then \
	{\
		tar -zxf $(1)/$(2)$(3) -C $(1)/ ;\
		rm $(1)/$(2)/install -f && ln -s `which install` $(1)/$(2)/install ; \
		cd $(1)/$(2) && ./configure $(4) && make -j8 && make install;\
	};\
	else echo "[1;32m" "$(2): nothing to do!!! " "[0;39m" ;\
	fi
endef


# path
define file-chk
	if [ -f $1 ]; then echo "y";\
	else echo "n";\
	fi
endef




# dir , lib name , suffix ,configure args
define auto_cmake_install_compressed_lib
	@echo "[1;33m" ">>>>>>> Build File: $(2)$(3)" "[0;39m" ;
	@set -x;
	tar -zxf $(1)/$(2)$(3) -C $(1)/ ;
	cd $(1)/$(2) && mkdir -p build && cd build && cmake $(4) .. && make -j8 && make install;
endef

# dir , lib name , suffix ,configure args
define auto_cmake_install_compressed_lib_once
	@echo "[1;33m" ">>>>>>> Build File: $(2)$(3)" "[0;39m" ;
	@set -x;
	@if [ ! -d $(1)/$(2) ]; then \
	{\
		tar -zxf $(1)/$(2)$(3) -C $(1)/ ;\
		cd $(1)/$(2) && mkdir -p build && cd build && cmake $(4) .. && make -j8 && make install;\
	};\
	else echo "[1;32m" "$(2): nothing to do!!! " "[0;39m" ;\
	fi
endef



