
obj-y :=
obj-y += mt_async_queue.o
obj-y += mt_msg.o
obj-y += mt_queue.o

obj-y += mt_broadcast.o
obj-y += mt_evdriver.o
obj-y += mt_mm.o
obj-y += mt_multicast.o
obj-y += mt_task.o
obj-y += mt_threadpool.o

